const trendingRecipes = [
    {
      id: 't1',
      title: 'Pork Sisig (Dinner)',
      image: 'https://www.ajinomoto.com.ph/ajinomoto-static/web/wp-content/uploads/2018/11/Pork-Sisig-2.jpg',
      rating: 4.9,
      type: 'Dinner',
    },
    {
      id: 't2',
      title: 'Lumpia Shanghai (Dinner)',
      image: 'https://th.bing.com/th/id/OIP.ULQ9HccYlnGTXX5GVGd24wAAAA?rs=1&pid=ImgDetMain',
      rating: 4.7,
      type: 'Dinner',
    },
    {
      id: 't3',
      title: 'Halo-Halo (Dessert)',
      image: 'https://c1.staticflickr.com/5/4139/4819196229_90ea592cc7_b.jpg',
      rating: 4.8,
      type: 'Dessert',
    },
    {
      id: 't4',
      title: 'Sago at Gulaman (Drinks)',
      image: 'https://www.recipesbynora.com/wp-content/uploads/2023/08/Sago-at-Gulaman-featured-image-1-720x720.jpg',
      rating: 4.6,
      type: 'Drinks',
    },
  ];
  
const filipinoRecipes = [
    {
      id: 'f1',
      title: 'Adobong Baboy',
      image: 'https://yummykitchentv.com/wp-content/uploads/2023/06/adobong-baboy-with-pineapples-recipe.jpg',
      description: 'A popular Filipino dish made with chicken or pork.',
      type: 'Lunch',
      details: {
        servings: '4-6 persons',
        cookTime: '45 mins',
        difficulty: 'Medium',
      },
      ingredients: [
        '1 kg pork belly, cut into 2-inch cubes',
        '1/2 cup soy sauce',
        '1/4 cup vinegar',
        '4 cloves garlic, minced',
        '1 tbsp whole peppercorns',
        '2 bay leaves',
        '1 tbsp cooking oil',
        'Water, as needed',
      ],
      instructions: [
        'In a pot, combine pork belly, soy sauce, vinegar, garlic, peppercorns, and bay leaves.',
        'Add enough water to cover the pork.',
        'Bring to a boil, then reduce heat and simmer until pork is tender and sauce has reduced, about 30-40 minutes.',
        'In a separate pan, heat cooking oil and lightly brown the cooked pork.',
        'Return the browned pork to the sauce and simmer for another 5 minutes.',
        'Serve hot with rice.',
      ],
      reviews: [
        { user: 'FoodieGal', rating: 5, comment: 'Authentic and delicious!' },
        { user: 'PorkLover', rating: 4, comment: 'A classic done right.' },
      ],
      video: '7fCrES-hP7I',
    },
    {
      id: 'f2',
      title: 'Sinigang na hipon',
      image: 'https://almostnordic.com/wp-content/uploads/2021/12/sinigang-na-hipon-recipe-1024x784.jpg',
      description: 'A savory and sour soup made with tamarind.',
      type: 'Lunch',
      details: {
        servings: '3-4 persons',
        cookTime: '30 mins',
        difficulty: 'Easy',
      },
      ingredients: [
        '1 kg shrimp, peeled and deveined',
        '1 large onion, quartered',
        '2 tomatoes, quartered',
        '1 bunch water spinach (kangkong)',
        '2 green long peppers (siling haba)',
        '1 pack (23g) tamarind soup base mix',
        'Fish sauce (patis) to taste',
        'Water, about 6 cups',
      ],
      instructions: [
        'In a pot, bring water to a boil.',
        'Add onion and tomatoes and simmer for 5 minutes.',
        'Stir in the tamarind soup base mix.',
        'Add the shrimp and cook until pink, about 3-5 minutes.',
        'Season with fish sauce to taste.',
        'Add water spinach and green long peppers. Cook until the vegetables are just wilted.',
        'Serve hot with rice.',
      ],
      reviews: [
        { user: 'SourSoupFan', rating: 5, comment: 'Perfectly sour and savory!' },
        { user: 'SeafoodKing', rating: 4, comment: 'Fresh and tasty shrimp sinigang.' },
      ],
      video: '7QKr1oy4Ykc',
    },
    {
      id: 'f3',
      title: 'Pork Sisig',
      image: 'https://www.ajinomoto.com.ph/ajinomoto-static/web/wp-content/uploads/2018/11/Pork-Sisig-2.jpg',
      description: 'A sizzling dish made from parts of a pig’s head and liver.',
      type: 'Dinner',
      details: {
        servings: '2-3 persons',
        cookTime: '35 mins',
        difficulty: 'Medium',
      },
      ingredients: [
        '500g pork belly, boiled and diced',
        '1/4 cup soy sauce',
        '2 tbsp calamansi juice',
        '1 small onion, chopped',
        '2 cloves garlic, minced',
        '1-2 red chilies, chopped (optional)',
        '2 tbsp mayonnaise',
        'Salt and pepper to taste',
        '1 egg (optional, for topping)',
      ],
      instructions: [
        'Heat a pan or griddle over medium heat.',
        'Grill or pan-fry the diced pork belly until slightly crispy.',
        'In a bowl, combine soy sauce, calamansi juice, chopped onion, garlic, and chilies (if using).',
        'Add the cooked pork to the bowl and mix well.',
        'Transfer the mixture to a sizzling plate or a regular pan.',
        'Stir in mayonnaise and season with salt and pepper.',
        'Top with a raw egg (optional) and serve immediately.',
      ],
      reviews: [
        { user: 'SizzlingKing', rating: 5, comment: 'The best sisig ever!' },
        { user: 'PorkAddict', rating: 4, comment: 'So flavorful and satisfying.' },
      ],
      video: 'bmniIkqmXok',
    },
    {
      id: 'f4',
      title: 'Lumpia Shanghai',
      image: 'https://th.bing.com/th/id/OIP.ULQ9HccYlnGTXX5GVGd24wAAAA?rs=1&pid=ImgDetMain',
      description: 'Small, deep-fried meat spring rolls that are popular as an appetizer or snack.',
      type: 'Dinner',
      details: {
        servings: '6-8 persons',
        cookTime: '30 mins',
        difficulty: 'Easy',
      },
      ingredients: [
        '500g ground pork',
        '1 small carrot, finely chopped',
        '1 small onion, finely chopped',
        '2 cloves garlic, minced',
        '1/4 cup water chestnuts, chopped',
        '1 egg, beaten',
        '2 tbsp soy sauce',
        '1 tsp salt',
        '1/2 tsp black pepper',
        'Lumpia wrappers',
        'Cooking oil, for frying',
      ],
      instructions: [
        'In a bowl, combine ground pork, carrot, onion, garlic, water chestnuts, beaten egg, soy sauce, salt, and pepper.',
        'Mix well until all ingredients are evenly distributed.',
        'Place a lumpia wrapper on a flat surface.',
        'Put a spoonful of the pork mixture near one corner of the wrapper.',
        'Fold the sides of the wrapper inward, then roll it up tightly.',
        'Seal the edge with a little water or beaten egg.',
        'Heat cooking oil in a deep pan over medium heat.',
        'Fry the lumpia in batches until golden brown and cooked through, about 3-5 minutes.',
        'Drain on paper towels and serve with your favorite dipping sauce.',
      ],
      reviews: [
        { user: 'LumpiaLover', rating: 5, comment: 'Crispy and delicious!' },
        { user: 'PartyFoodie', rating: 4, comment: 'Always a hit at parties.' },
      ],
      video: 'jFyZp7yqtVU',
    },
    // Dessert
    {
      id: 'f5',
      title: 'Leche Flan',
      image: 'https://bitesbybianca.com/wp-content/uploads/2024/12/filipino-leche-flan-cover-1.jpg',
      description: 'A rich custard dessert with a soft caramel topping, similar to crème caramel.',
      type: 'Dessert',
      details: {
        servings: '6-8 servings',
        cookTime: '1 hour 30 mins',
        difficulty: 'Medium',
      },
      ingredients: [
        '10 egg yolks',
        '1 can (14 oz) condensed milk',
        '1 can (12 oz) evaporated milk',
        '1 tsp vanilla extract',
        '1 cup granulated sugar',
        '1/4 cup water',
      ],
      instructions: [
        'Prepare the caramel: In a saucepan, combine sugar and water over medium heat. Stir until sugar is dissolved, then let it simmer without stirring until it turns into a light golden caramel. Pour the caramel evenly into the bottom of your molds (llaneras or ramekins).',
        'Prepare the custard: In a large bowl, whisk the egg yolks until light yellow.',
        'Gradually add the condensed milk and evaporated milk, mixing well after each addition.',
        'Stir in the vanilla extract.',
        'Pour the custard mixture over the caramel in the molds, filling them almost to the top.',
        'Steam the leche flan: Cover the molds tightly with aluminum foil. Arrange them in a steamer with boiling water reaching halfway up the sides of the molds. Steam for 45-60 minutes, or until a toothpick inserted into the center comes out clean.',
        'Alternatively, bake the leche flan: Preheat oven to 325°F (160°C). Place the molds in a baking dish and pour hot water into the dish until it reaches halfway up the sides of the molds (water bath). Bake for 50-60 minutes, or until a toothpick inserted into the center comes out clean.',
        'Cool completely: Let the leche flan cool at room temperature, then refrigerate for at least 2 hours or until thoroughly chilled.',
        'Unmold: To unmold, run a thin knife around the edges of the mold. Place a serving plate upside down over the mold and quickly flip it over. The caramel should be on top.',
        'Serve chilled and enjoy!',
      ],
      reviews: [
        { user: 'SweetTooth', rating: 5, comment: 'So creamy and delicious!' },
        { user: 'DessertKing', rating: 4, comment: 'Perfectly sweet and smooth.' },
      ],
      video: 'iDJxsbWzrY4',
    },
    {
      id: 'f6',
      title: 'Halo-Halo',
      image: 'https://c1.staticflickr.com/5/4139/4819196229_90ea592cc7_b.jpg',
      description: 'A popular Filipino cold dessert made up of mixtures of ice and various toppings.',
      type: 'Dessert',
      details: {
        servings: '1 serving',
        cookTime: '15 mins (preparation)',
        difficulty: 'Easy',
      },
      ingredients: [
        '1/2 cup shaved ice',
        '2 tbsp cooked sweet beans',
        '2 tbsp cooked garbanzos',
        '2 tbsp kaong (sugar palm fruit), sweetened',
        '2 tbsp macapuno (coconut sport), sweetened',
        '2 tbsp nata de coco (coconut gel), sweetened',
        '2 tbsp leche flan, cubed',
        '2 tbsp ube halaya (purple yam jam)',
        '2 tbsp sweet corn kernels',
        '1 scoop ube ice cream',
        '1 tbsp pinipig (toasted pounded young rice)',
        'Evaporated milk, to taste',
        'Optional toppings: langka (jackfruit), banana slices, etc.',
      ],
      instructions: [
        'In a tall glass or bowl, layer the sweet beans, garbanzos, kaong, macapuno, and nata de coco at the bottom.',
        'Add the cubed leche flan, ube halaya, and sweet corn kernels.',
        'Fill the glass with shaved ice.',
        'Pour evaporated milk over the shaved ice to your liking.',
        'Top with a scoop of ube ice cream and sprinkle with pinipig.',
        'Add any other optional toppings you desire.',
        'Serve immediately and mix well before eating to enjoy all the flavors together!',
      ],
      reviews: [
        { user: 'CoolDesserts', rating: 5, comment: 'The perfect refreshing treat!' },
        { user: 'HaloHaloFan', rating: 5, comment: 'So many delicious textures and flavors.' },
      ],
      video: '_pjVolzdxzU',
    },
    // Drinks
    {
      id: 'f7',
      title: 'Sago at Gulaman',
      image: 'https://www.recipesbynora.com/wp-content/uploads/2023/08/Sago-at-Gulaman-featured-image-1-720x720.jpg',
      description: 'A popular Filipino cold beverage made with tapioca pearls (sago) and agar-agar jelly (gulaman) in a sweet caramel syrup.',
      type: 'Drinks',
      details: {
      servings: '4-6 servings',
      cookTime: '30 mins',
      difficulty: 'Easy',
    },
    ingredients: [
      '1/2 cup small pearl sago (tapioca pearls)',
      '1 bar (25g) agar-agar jelly powder, unflavored',
      '4 cups water (for jelly)',
      '1 cup brown sugar',
      '1 cup water (for syrup)',
      'Pandan leaves (optional, for aroma)',
      'Ice cubes',
    ],
    instructions: [
      'Cook the sago: Bring a pot of water to a boil. Add the sago and cook until they become transparent. Drain and rinse with cold water to stop the cooking process. Set aside.',
      'Prepare the gulaman (jelly): In a saucepan, combine the agar-agar powder and 4 cups of water. Bring to a boil, stirring constantly until the powder is fully dissolved. Pour the mixture into a shallow container and let it cool and set completely. Once set, cut the jelly into small cubes.',
      'Make the caramel syrup: In another saucepan, combine the brown sugar and 1 cup of water. Add pandan leaves if using. Bring to a boil and simmer for 5-10 minutes, or until the syrup slightly thickens. Let it cool completely.',
      'Assemble the drink: In individual glasses, put some cooked sago and gulaman cubes.',
      'Pour the cooled caramel syrup over the sago and gulaman.',
      'Add ice cubes to chill the drink.',
      'Serve immediately and enjoy!',
    ],
    reviews: [
      { user: 'ThirstyGuy', rating: 4, comment: 'A classic refreshing drink.' },
      { user: 'SweetDrinks', rating: 5, comment: 'Perfectly sweet and chewy.' },
    ],
    video: 'OAAV_Bs1QaY',
    },
    {
      id: 'f8',
      title: 'Buko Juice',
      image: 'https://ph-test-11.slatic.net/p/1e770c2662e5ecad0307d3c5f640a327.jpg',
      description: 'The clear, refreshing liquid found inside young coconuts.',
      type: 'Drinks',
      details: {
        servings: '2-3 servings',
        cookTime: '10 mins',
        difficulty: 'Easy',
      },
      ingredients: [
        '2-3 young coconuts',
        'Optional: Sugar or sweetener to taste',
        'Ice cubes',
      ],
      instructions: [
        'Open the young coconuts carefully and pour the buko water (coconut juice) into a pitcher or glasses.',
        'Scoop out the soft coconut meat from the inside of the coconuts and add it to the juice.',
        'Taste the juice and add sugar or your preferred sweetener if desired, stirring until dissolved.',
        'Add ice cubes to chill the buko juice.',
        'Serve immediately and enjoy the natural refreshment!',
      ],
      reviews: [
        { user: 'CoconutLover', rating: 5, comment: 'The best way to cool down!' },
        { user: 'NaturalDrinks', rating: 4, comment: 'So refreshing and healthy.' },
      ],
      video: '0SSpB9AW_zQ',
    },
    // Meals
    {
      id: 'f9',
      title: 'Pancit Bihon',
      image: 'https://i.pinimg.com/originals/7f/c2/b2/7fc2b29e0a2c556295ad89339d9f766e.jpg',
      description: 'A Filipino stir-fried rice noodle dish with various vegetables and meat.',
      type: 'Appetizers',
      details: {
        servings: '4-6 servings',
        cookTime: '30 mins',
        difficulty: 'Easy',
      },
      ingredients: [
        '300g bihon (thin rice noodles)',
        '2 tbsp cooking oil',
        '1 small onion, sliced',
        '2 cloves garlic, minced',
        '1 cup sliced carrots',
        '1 cup sliced bell peppers (any color)',
        '1 cup shredded cabbage',
        '1/2 cup sliced green beans',
        '200g cooked chicken or pork, shredded',
        '4 cups chicken broth',
        '1/4 cup soy sauce',
        '2 tbsp fish sauce (patis)',
        'Salt and pepper to taste',
        'Calamansi or lemon wedges, for serving',
        'Optional toppings: hard-boiled eggs, shrimp, scallions',
      ],
      instructions: [
        'Soak the bihon noodles in warm water for about 15-20 minutes until softened. Drain well and set aside.',
        'Heat cooking oil in a large wok or pan over medium heat. Sauté the onion and garlic until fragrant.',
        'Add the sliced carrots, bell peppers, green beans, and shredded cabbage. Stir-fry for 3-5 minutes until the vegetables are slightly tender-crisp.',
        'Add the shredded chicken or pork and continue to stir-fry for another minute.',
        'Pour in the chicken broth, soy sauce, and fish sauce. Bring to a boil, then reduce heat and simmer for 5-7 minutes.',
        'Add the soaked and drained bihon noodles to the pan. Toss gently to coat the noodles with the sauce. Cook until the noodles are tender and have absorbed most of the liquid. Season with salt and pepper to taste.',
        'Transfer the pancit bihon to a serving platter.',
        'Garnish with optional toppings like sliced hard-boiled eggs, shrimp, and chopped scallions.',
        'Serve hot with calamansi or lemon wedges on the side for squeezing.',
      ],
      reviews: [
        { user: 'NoodleFan', rating: 5, comment: 'A delicious and satisfying noodle dish!' },
        { user: 'FilipinoFoodie', rating: 4, comment: 'Classic pancit bihon, always a favorite.' },
      ],
      video: 'Rwu0nM8F_sE',
    },
    {
      id: 'f10',
      title: 'Laing',
      image: 'https://1.bp.blogspot.com/-rj5O8F3OeiQ/WLtiKI6QaZI/AAAAAAAAAb8/09hUX_olMNsFHwxi-YLjTL0I85wJnlNnACLcB/s1600/laing.jpg',
      description: 'A Filipino vegetable stew made from taro leaves cooked in coconut milk, chili, garlic, ginger, and shrimp paste.',
      type: 'Lunch',
      details: {
        servings: '4-6 servings',
        cookTime: '1-2 hours',
        difficulty: 'Medium',
        },
        ingredients: [
            '2 cups dried taro leaves (gabi leaves)',
            '2 cups coconut milk (first extract)',
            '4 cups coconut milk (second extract)',
            '1 large onion, chopped',
            '5 cloves garlic, minced',
            '1 inch ginger, minced',
            '2-3 red chilies (labuyo), chopped (adjust to spice preference)',
            '1/4 cup shrimp paste (bagoong alamang)',
            'Salt and pepper to taste',
            'Optional: Pork belly or shrimp, cubed',
          ],
          instructions: [
            'Wash the dried taro leaves thoroughly and soak them in water for at least 30 minutes to soften.',
            'If using pork belly or shrimp, sauté them in a pot until lightly browned. Remove and set aside.',
            'In the same pot, sauté the onion, garlic, and ginger until fragrant.',
            'Add the chopped red chilies and shrimp paste. Cook for a minute, stirring constantly.',
            'Add the softened taro leaves to the pot. Pour in the second extract of coconut milk.',
            'Bring to a boil, then reduce heat to low, cover, and simmer for 1 to 1.5 hours, or until the taro leaves are very tender and the liquid has reduced significantly. Stir occasionally to prevent sticking.',
            'Add the first extract of coconut milk and the cooked pork belly or shrimp (if using). Continue to simmer uncovered for another 15-20 minutes, stirring occasionally, until the sauce is thick and creamy.',
            'Season with salt and pepper to taste. Be mindful of the saltiness of the shrimp paste.',
            'Serve hot with rice.',
          ],
          reviews: [
            { user: 'CoconutFan', rating: 5, comment: 'Rich, creamy, and perfectly spiced!' },
            { user: 'VeggieLover', rating: 4, comment: 'A unique and flavorful vegetable dish.' },
          ],
          video: 'sUgwuoiT3RU',
    },
    {
      id: 'f11',
      title: 'Chicken Adobo',
      image: 'https://www.foxyfolksy.com/wp-content/uploads/2014/03/Filipino-Adobo-1200t.jpg',
      description: 'A savory and tangy chicken stew, a Filipino classic.',
      type: 'Lunch',
      details: { servings: '4-6 persons', cookTime: '1 hour', difficulty: 'Medium' },
      ingredients: [
        '750g boneless chicken thighs',
        '1/3 cup soy sauce',
        '1/3 cup + 2 tbsp white vinegar',
        '6 garlic cloves (3 for marinating, 3 for cooking)',
        '4 bay leaves',
        '2 tbsp cooking oil',
        '1 small onion, diced',
        '1 1/2 cups water',
        '2 tbsp brown sugar',
        '1 tsp black peppercorns',
      ],
      instructions: [
        'Marinate chicken in soy sauce, vinegar, 3 garlic cloves, bay leaves, and peppercorns for 30 minutes.',
        'Heat oil in a pan, sauté onion and remaining garlic until fragrant.',
        'Add chicken (reserve marinade) and brown on all sides.',
        'Pour in marinade and water, bring to a boil, then simmer for 30 minutes.',
        'Stir in brown sugar and cook until sauce thickens.',
        'Serve hot with rice.',
      ],
      video: 'wwapBsT0oc8',
    },
    {
      id: 'f12',
      title: 'Sinigang na Baboy',
      image: 'https://images.yummy.ph/yummy/uploads/2019/03/sinigangbaboysamiso-recipe-1.jpg',
      description: 'A sour pork soup with tamarind and vegetables.',
      type: 'Lunch',
      details: { servings: '4-6 persons', cookTime: '1 hour 30 mins', difficulty: 'Medium' },
      ingredients: [
        '1 kg pork ribs',
        '1 pack tamarind soup mix (40g)',
        '1 onion, quartered',
        '2 tomatoes, quartered',
        '1 radish, sliced',
        '1 bundle kangkong (water spinach)',
        '1 eggplant, sliced',
        '6 cups water',
        '1 tbsp fish sauce',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Boil pork ribs in water with onion and tomatoes for 1 hour until tender.',
        'Add tamarind soup mix and fish sauce, stir well.',
        'Add radish and eggplant, cook for 10 minutes.',
        'Add kangkong and simmer for 2 minutes.',
        'Season with salt and pepper.',
        'Serve hot with rice.',
      ],
      video: 't-beBtUZz3E',
    },
    {
      id: 'f13',
      title: 'Beef Caldereta',
      image: 'https://kitchenomics.com/media/catalog/product/C/a/Caldereta_2.jpg',
      description: 'A spicy beef stew with tomato sauce and liver spread.',
      type: 'Dinner',
      details: { servings: '4-6 persons', cookTime: '2 hours', difficulty: 'Medium' },
      ingredients: [
        '1 kg beef, cubed',
        '1 onion, chopped',
        '3 garlic cloves, minced',
        '2 cups tomato sauce',
        '1/4 cup liver spread',
        '2 potatoes, cubed',
        '2 carrots, sliced',
        '1 red bell pepper, sliced',
        '1/2 cup green peas',
        '2 tbsp cooking oil',
        '2 cups water',
        '2 bay leaves',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Heat oil, sauté garlic and onion until soft.',
        'Add beef and brown on all sides.',
        'Pour in tomato sauce, water, and bay leaves. Simmer for 1.5 hours.',
        'Add liver spread, potatoes, and carrots. Cook for 15 minutes.',
        'Add bell pepper and peas, cook for 5 minutes.',
        'Season and serve hot with rice.',
      ],
      video: 'rzrjAXluUj4',
    },
    {
      id: 'f14',
      title: 'Kare-Kare',
      image: 'https://www.kuserrano.com/wp-content/uploads/2023/04/bagnet-kare-kare.jpg',
      description: 'A peanut-based stew with oxtail and vegetables.',
      type: 'Dinner',
      details: { servings: '4-6 persons', cookTime: '2 hours 30 mins', difficulty: 'Hard' },
      ingredients: [
        '1 kg oxtail, cut into pieces',
        '1/2 cup peanut butter',
        '1 onion, chopped',
        '3 garlic cloves, minced',
        '1 eggplant, sliced',
        '1 bundle string beans',
        '1 banana heart, sliced',
        '1/4 cup annatto powder',
        '4 cups beef broth',
        '2 tbsp cooking oil',
        'Bagoong for serving',
      ],
      instructions: [
        'Boil oxtail in beef broth for 2 hours until tender.',
        'Heat oil, sauté garlic and onion.',
        'Add oxtail and broth, stir in peanut butter and annatto powder.',
        'Add eggplant, string beans, and banana heart. Cook for 10 minutes.',
        'Serve with bagoong on the side.',
      ],
      video: 'No9mUME9u0U',
    },
    {
      id: 'f15',
      title: 'Pancit Canton',
      image: 'https://assets.unileversolutions.com/v1/80633505.jpg',
      description: 'Stir-fried egg noodles with vegetables and chicken.',
      type: 'Appetizers',
      details: { servings: '4-6 persons', cookTime: '30 mins', difficulty: 'Easy' },
      ingredients: [
        '250g pancit canton noodles',
        '200g chicken breast, sliced',
        '1 carrot, julienned',
        '1/2 cabbage, shredded',
        '1 bell pepper, sliced',
        '1 onion, sliced',
        '3 garlic cloves, minced',
        '3 tbsp soy sauce',
        '2 tbsp oyster sauce',
        '2 cups chicken broth',
        '2 tbsp cooking oil',
      ],
      instructions: [
        'Heat oil, sauté garlic, onion, and chicken until cooked.',
        'Add carrots, cabbage, and bell pepper. Stir-fry for 5 minutes.',
        'Pour in soy sauce, oyster sauce, and broth. Bring to a boil.',
        'Add noodles and cook until liquid is absorbed, about 5 minutes.',
        'Serve hot.',
      ],
      video: '6-b6h_LoJyg',
    },
    {
      id: 'f16',
      title: 'Lumpiang Togue',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3-Ehac8hhCveZDLE7nZaPLqzwuf2faOD7ZQ&s',
      description: 'Crispy spring rolls filled with mung bean sprouts.',
      type: 'Appetizers',
      details: { servings: '6-8 persons', cookTime: '40 mins', difficulty: 'Easy' },
      ingredients: [
        '2 cups mung bean sprouts (togue), rinsed and drained',
        '1 small carrot, julienned',
        '1/2 cup green beans, thinly sliced',
        '1 small onion, minced',
        '3 garlic cloves, minced',
        '1/4 cup small shrimp, peeled (optional)',
        '2 tbsp soy sauce',
        '1 tsp fish sauce',
        '20 lumpia wrappers',
        'Oil for frying',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Heat oil in a pan, sauté garlic and onion until fragrant.',
        'Add shrimp (if using) and cook until pink, about 2 minutes.',
        'Add mung bean sprouts, carrots, and green beans. Stir-fry for 3-4 minutes until tender-crisp.',
        'Season with soy sauce, fish sauce, salt, and pepper. Remove from heat and let cool slightly.',
        'Place 1-2 tbsp of the filling on a lumpia wrapper. Fold the sides inward and roll tightly.',
        'Seal the edge with water or a cornstarch-water mixture.',
        'Heat oil in a deep pan over medium heat. Fry the lumpia in batches until golden brown, about 3-5 minutes.',
        'Drain on paper towels and serve with spiced vinegar dipping sauce.',
      ],
      video: 'x_ERVgcZpvI',
    },
    {
      id: 'f17',
      title: 'Lechon Kawali',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCy-wytqwPPIvsUnFLqZ9HyidTSGDRhFZRtw&s',
      description: 'Crispy fried pork belly with a crunchy skin.',
      type: 'Dinner',
      details: { servings: '4-6 persons', cookTime: '1 hour 30 mins', difficulty: 'Medium' },
      ingredients: [
        '1 kg pork belly',
        '1 tbsp salt',
        '1 tsp peppercorns',
        '2 bay leaves',
        'Water for boiling',
        'Oil for frying',
      ],
      instructions: [
        'Boil pork belly with salt, peppercorns, and bay leaves for 1 hour.',
        'Drain and air-dry for 2 hours.',
        'Heat oil and deep-fry pork until crispy, about 10 minutes.',
        'Chop and serve with liver sauce.',
      ],
      video: 'pP1h0zRsIek',
    },
    {
      id: 'f18',
      title: 'Chicken Inasal',
      image: 'https://theodehlicious.com/wp-content/uploads/2023/12/Bacolod-Chicken-Inasal.jpg',
      description: 'Grilled chicken with a tangy marinade.',
      type: 'Dinner',
      details: { servings: '4-6 persons', cookTime: '1 hour', difficulty: 'Medium' },
      ingredients: [
        '1 kg chicken thighs',
        '1/4 cup calamansi juice',
        '1/4 cup vinegar',
        '3 tbsp soy sauce',
        '3 garlic cloves, minced',
        '1 tbsp ginger, grated',
        '1 tsp annatto powder',
        '2 tbsp brown sugar',
        'Oil for grilling',
      ],
      instructions: [
        'Marinate chicken in calamansi, vinegar, soy sauce, garlic, ginger, annatto, and sugar for 2 hours.',
        'Preheat grill and brush with oil.',
        'Grill chicken for 10 minutes per side until cooked.',
        'Serve with soy-vinegar dip.',
      ],
      video: '6eUxhXa5-_M',
    },
    {
      id: 'f19',
      title: 'Bicol Express',
      image: 'https://panlasangpinoy.com/wp-content/uploads/2021/04/Bicol-Express-1.jpg',
      description: 'Spicy pork stew with coconut milk and chilies.',
      type: 'Lunch',
      details: { servings: '4-6 persons', cookTime: '1 hour', difficulty: 'Medium' },
      ingredients: [
        '500g pork belly, cubed',
        '2 cups coconut milk',
        '1 onion, chopped',
        '3 garlic cloves, minced',
        '10 green chilies, sliced',
        '2 tbsp shrimp paste',
        '2 tbsp cooking oil',
        'Salt to taste',
      ],
      instructions: [
        'Heat oil, sauté garlic and onion.',
        'Add pork and cook until browned.',
        'Stir in shrimp paste and coconut milk. Simmer for 20 minutes.',
        'Add chilies and cook for 5 minutes.',
        'Season with salt and serve with rice.',
      ],
      video: 'EglwOEDdsHU',
    },
    {
      id: 'f20',
      title: 'Bibingka',
      image: 'https://peotraco.com/wp-content/uploads/2020/09/Recipes-Image-Bibingka.jpg',
      description: 'A soft rice cake topped with salted egg and cheese.',
      type: 'Dessert',
      details: { servings: '6-8 servings', cookTime: '45 mins', difficulty: 'Medium' },
      ingredients: [
        '2 cups rice flour',
        '1 cup sugar',
        '1 tbsp baking powder',
        '3 eggs',
        '1 cup coconut milk',
        '1/4 cup melted butter',
        '1 salted egg, sliced',
        '1/4 cup grated cheese',
        'Banana leaves for lining',
      ],
      instructions: [
        'Preheat oven to 350°F (175°C). Line molds with banana leaves.',
        'Mix rice flour, sugar, and baking powder in a bowl.',
        'Whisk eggs, coconut milk, and melted butter. Combine with dry ingredients.',
        'Pour batter into molds, top with salted egg slices and cheese.',
        'Bake for 25-30 minutes until golden.',
        'Serve warm.',
      ],
      video: 'Yd4wcX7MlrE',
    },
  ];

  export {trendingRecipes, filipinoRecipes};